# vectorization

In [1]:
import numpy as np
import time

a= np.random.rand(1000000)
b= np.random.rand(1000000)

tic=time.time()
c=np.dot(a,b)
toc=time.time()

print(c)
print("vectorized version:"+str(1000*(toc-tic))+"ms")

c=0
tic=time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc=time.time()

print(c)
print("for loop:"+str(1000*(toc-tic))+"ms")

249781.57075730307
vectorized version:18.9511775970459ms
249781.5707573119
for loop:745.0058460235596ms


# broadcasting

In [1]:
import numpy as np
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print(c.shape)

(12288, 45)


In [2]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
c.shape

(3, 3)

In [8]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
print(a)
print(b)
a.sum(axis=0)


[[-0.09237785  0.82987785  0.98020134]
 [-0.3050937   1.34505124 -1.3337499 ]
 [-0.75453306  0.55912719 -0.28250065]
 [ 0.2496877  -1.83661998 -1.69628638]]
[[-0.87156374  1.86279881]
 [ 0.10222144  1.74714202]
 [-0.08758477  0.21600897]]


array([-0.90231691,  0.8974363 , -2.33233558])

In [9]:
a.sum(axis=1)

array([ 1.71770134, -0.29379236, -0.47790651, -3.28321865])

# Vectors

In [10]:
a = np.random.randn(5)
print(a)

[-1.14996283 -1.98032224  0.93286642 -0.97006197 -0.44510561]


In [11]:
print(a.shape)

(5,)


In [12]:
print(a.T)

[-1.14996283 -1.98032224  0.93286642 -0.97006197 -0.44510561]


In [13]:
print(np.dot(a,a.T))

7.253469685531723


In [15]:
a = np.random.randn(5,1)
print(a)

[[ 0.11026415]
 [-0.69903691]
 [ 0.73039507]
 [-0.67710371]
 [-0.10460553]]


In [16]:
print(a.T)

[[ 0.11026415 -0.69903691  0.73039507 -0.67710371 -0.10460553]]


In [17]:
print(np.dot(a,a.T))

[[ 0.01215818 -0.07707871  0.08053639 -0.07466026 -0.01153424]
 [-0.07707871  0.4886526  -0.51057311  0.47332048  0.07312313]
 [ 0.08053639 -0.51057311  0.53347695 -0.49455321 -0.07640337]
 [-0.07466026  0.47332048 -0.49455321  0.45846943  0.07082879]
 [-0.01153424  0.07312313 -0.07640337  0.07082879  0.01094232]]


In [18]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b
print(c.shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 